version: '3.8'
services:
    webserver:
        image: webserver
        depends_on:
            - database
        container_name: ${PREFIX}webserver
        expose:
            - "${REDCAP_PORT}"
        ports:
            - "${REDCAP_PORT}:80"
        restart: always
        env_file: .env
        volumes:
            - webserver:/var/www/html/redcap
        networks:
            - network

    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin
        restart: always
        container_name: ${PREFIX}phpmyadmin
        env_file: .env
        expose:
            - "${PHPMYADMIN_PORT}"
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        networks:
            - network

    database:
        image: mysql
        restart: always
        container_name: ${PREFIX}database
        env_file: .env
        volumes:
            - mysql_datavolume:/var/lib/mysql
        networks:
            - network

    cron:
        depends_on:
            - database
        image: cron
        container_name: ${PREFIX}cron
        restart: always
        env_file: .env
        volumes:
            # - /tsd/pXX/data/durable/database/redcap_backup:/backup
            - /Users/ju/Downloads/redcap/test:/backup
        networks:
            - network

volumes:
    mysql_datavolume:
        name: ${PREFIX}mysql_datavolume
    webserver:
        name: ${PREFIX}webserver

networks:
    network:
        name: "${PREFIX}network"
