version: '3.4'
services:
    webserver:
        image: webserver
        depends_on:
            - database
        expose:
            - "8000"
        ports: 
            - "8000:80"
        links:
            - database
        restart: always
        volumes:
            - redcap_webserver:/var/www/html/redcap    
                    
    phpmyadmin:
        depends_on: 
            - database
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        expose:
            - "9000"
        ports:
            - "9000:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        links:
            - database
                
    database:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: norment123
            MYSQL_DATABASE: redcap
        restart: always
        volumes:
            # https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-
            # by default volumes are created here: /var/lib/docker/volumes, i.e. locally on the pNN-service-l VM
            # this is fine, i.e. we don't need to map this to /ess/pNN storage.
            - redcap_mysql_datavolume:/var/lib/mysql

volumes:
    redcap_mysql_datavolume:
    redcap_webserver: # location of redcap files



            
