version: '3.8'
services:
    webserver:
        image: webserver
        depends_on:
            - database
        expose:
            - "${MYSQL_PORT_WEBSERVER}"
        ports: 
            - "${MYSQL_PORT_WEBSERVER}:80"
        restart: always
        env_file: .env 
        volumes:
            - redcap_webserver:/var/www/html/redcap    
                    
    phpmyadmin:
        depends_on: 
            - database
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        env_file: .env        
        expose:
            - "${MYSQL_PORT_PMA}"
        ports:
            - "${MYSQL_PORT_PMA}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306            
                
    database:
        image: mysql
        restart: always
        env_file: .env
        volumes:
            - redcap_mysql_datavolume:/var/lib/mysql

    cron:
        depends_on: 
            - database
        image: cron        
        restart: always
        env_file: .env
        volumes:        
            - /tsd/pXX/data/durable/database/redcap_backup:/backup

volumes:
    redcap_mysql_datavolume:
    redcap_webserver:
