version: '3.8'
services:
    webserver:
        image: webserver
        depends_on:
            - database
        expose:
            - "8000"
        ports: 
            - "8000:80"
        restart: always
        env_file: .env 
        volumes:
            - redcap_webserver:/var/www/html/redcap    
                    
    phpmyadmin:
        depends_on: 
            - database
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        env_file: .env        
        expose:
            - "9000"
        ports:
            - "9000:80"
                
    database:
        image: mysql
        restart: always
        env_file: .env
        volumes:
            - redcap_mysql_datavolume:/var/lib/mysql

    cron:
        depends_on: 
            - database
        image: cron        
        restart: always
        env_file: .env
        volumes:
            - /Users/ju/Downloads/redcap/test:/backup
        
volumes:
    redcap_mysql_datavolume:
    redcap_webserver:
