version: '3.4'
services:
    webserver:
        image: webserver_redcap
        depends_on:
            - db
        expose:
            - "8000"
        ports: 
            - "8000:80"
        links:
            - db
        restart: always
            
    pma:
        depends_on: 
            - db
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        expose:
            - "9000"
        ports:
            - "9000:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        links:
            - db
                
    db: 
        image: mysql_redcap
        environment:
            MYSQL_ROOT_PASSWORD: norment123
            MYSQL_DATABASE: redcap
        restart: always
     

