version: '3.4'
services:
    webserver:
        image: webserver
        depends_on:
            - database
        expose:
            - "8000"
        ports: 
            - "8000:80"
        restart: always
        volumes:
            - redcap_webserver:/var/www/html/redcap    
                    
    phpmyadmin:
        depends_on: 
            - database
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        expose:
            - "9000"
        ports:
            - "9000:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
                
    database:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: norment123
            MYSQL_DATABASE: redcap
        restart: always
        volumes:
            - redcap_mysql_datavolume:/var/lib/mysql

volumes:
    redcap_mysql_datavolume:
    redcap_webserver: # location of redcap files



            
